#!/usr/bin/python3
# raise name exception together with message
def raise_exception_msg(message=""):
    raise NameError(message)
